spring:
  application:
    name: payme
  datasource:
    url: jdbc:postgresql://localhost:5432/payme
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true